### PR TITLE
Fix selinux_not_disabled remediation to preserve enforcing state

### LINKED ISSUE #14368: RHEL 10 CIS Server L1 remediation forces SELINUX=permissive (overrides Kickstart selinux --enforcing)
### **Product/Version**
- RHEL 10.1
- scap-security-guide-0.1.79-2.el10.noarch
- OpenSCAP: `oscap --version` (please see attached):  [oscap-version.txt](https://github.com/user-attachments/files/25171029/oscap-version.txt)

### **Profile**
- `xccdf_org.ssgproject.content_profile_cis_server_l1`
- Content: `/usr/share/xml/scap/ssg/content/ssg-rhel10-ds.xml`

### **Problem**
When generating a remediation script and applying it during Kickstart %post, the system boots into **Permissive** even though Kickstart specifies `selinux --enforcing`.

### **Reproduce**
```bash
oscap xccdf generate fix \
  --profile xccdf_org.ssgproject.content_profile_cis_server_l1 \
  --fix-type bash \
  /usr/share/xml/scap/ssg/content/ssg-rhel10-ds.xml > /root/openscap/remediation.sh

bash /root/openscap/remediation.sh
```

### **Evidence (from generated remediation.sh)**

```bash
###############################################################################
# BEGIN fix (231 / 321) for 'xccdf_org.ssgproject.content_rule_selinux_not_disabled'
###############################################################################
(>&2 echo "Remediating rule 231/321: 'xccdf_org.ssgproject.content_rule_selinux_not_disabled'"); (
# Remediation is applicable only in certain platforms
if rpm --quiet -q kernel-core; then

if [ -e "/etc/selinux/config" ] ; then
    
    LC_ALL=C sed -i "/^SELINUX=/Id" "/etc/selinux/config"
else
    touch "/etc/selinux/config"
fi
# make sure file has newline at the end
sed -i -e '$a\' "/etc/selinux/config"

cp "/etc/selinux/config" "/etc/selinux/config.bak"
# Insert at the end of the file
printf '%s\n' "SELINUX=permissive" >> "/etc/selinux/config"
# Clean up after ourselves.
rm "/etc/selinux/config.bak"

fixfiles onboot

else
    >&2 echo 'Remediation is not applicable, nothing was done'
fi
```

### **Actual result** 
/etc/selinux/config contains SELINUX=permissive and the host runs in permissive after first boot.

### **Expected result** 
The CIS "not disabled" rule should not force permissive. At minimum it should preserve existing state if already enforcing.

### **Notes** 
- RHEL 9 CIS Server L1 does not exhibit this behavior in our environment.
- I plan to work around the issue by updating the remediation script post generation to set SELinux to "enforcing"

### PR DESCRIPTION
**Pull request by Arden97**
#### Description:

- The `selinux_not_disabled` rule remediation has been modified to preserve the current SELinux state when it is already set to `enforcing` or `permissive`

#### Rationale:

- The rule's OVAL check accepts both `enforcing` and `permissive` as compliant states
- When users generate a full remediation script using `oscap xccdf generate fix`, the script includes remediations for all rules in the profile, regardless of current compliance status
- Without additional verification, the rule `selinux_not_disabled` forces `permissive` SELinux mode on a system
- Fixes #14368

#### Review Hints:

- manual verification is recommended
- use `build_product` script to build `/build/<product>/fixes/bash/selinux_not_disabled.sh` remediation
- execute resulted script on any rhel virtual machine with `enforcing` or `permissive` SELInux state
- make sure, that SELinux preserves it's state after execution

### CODE REVIEW

File: linux_os/guide/system/selinux/selinux_not_disabled/bash/shared.sh [hunk 1]
```diff
@@ -4,6 +4,16 @@
...
-{{{ bash_selinux_config_set(parameter="SELINUX", value="permissive", rule_id=rule_id) }}}
+# Check current SELinux state in config file
+selinux_current_state=""
+if [ -f "/etc/selinux/config" ]; then
+    selinux_current_state=$(grep -oP '^\s*SELINUX=\K(enforcing|permissive|disabled)' /etc/selinux/config || true)
+fi
 
-fixfiles onboot
+# Only remediate if SELinux is disabled or not configured
+# If already set to enforcing or permissive, it's compliant - preserve the current state
```
Comment (jan-cerny) [inline linux_os/guide/system/selinux/selinux_not_disabled/bash/shared.sh:14]: Don't forget to update the warning in rule.yml accordingly.

**Review by jan-cerny — APPROVED** [review]
I believe this is a good fix for the issue
