### PR TITLE
Unify the RHEL approach for rule file_permissions_var_log_audit

### LINKED ISSUE #8948: Test scenarios for file_permissions_var_log_audit fail on RHEL7 and RHEL9
#### Description of problem:
```
INFO - xccdf_org.ssgproject.content_rule_file_permissions_var_log_audit
ERROR - Script correct_value_0600.pass.sh using profile (all) found issue:
ERROR - Rule evaluation resulted in fail, instead of expected pass during initial stage 
ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_file_permissions_var_log_audit'.
ERROR - Script correct_value_default_file_0600.pass.sh using profile (all) found issue:
ERROR - Rule evaluation resulted in fail, instead of expected pass during initial stage 
ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_file_permissions_var_log_audit'.
INFO - Script incorrect_value_0600.fail.sh using profile (all) OK
ERROR - Bash remediation for rule xccdf_org.ssgproject.content_rule_file_permissions_var_log_audit has exited with these errors:
Warning: Permanently added '192.168.122.111' (ECDSA) to the list of known hosts.
+ echo 'Remediating rule 1/1: '\''xccdf_org.ssgproject.content_rule_file_permissions_var_log_audit'\'''
Remediating rule 1/1: 'xccdf_org.ssgproject.content_rule_file_permissions_var_log_audit'
+ rpm --quiet -q audit
+ LC_ALL=C
+ grep -iw '^log_file' /etc/audit/auditd.conf
++ awk -F = '/^log_file/ {print $2}' /etc/audit/auditd.conf
++ tr -d ' '
+ FILE=/var/log/audit/audit2.log
+ LC_ALL=C
+ grep -m 1 -q '^log_group' /etc/audit/auditd.conf
++ awk -F = '/log_group/ {print $2}' /etc/audit/auditd.conf
++ tr -d ' '
+ GROUP=root
+ '[' root == root ']'
+ chmod 0600 /var/log/audit/audit2.log
+ chmod 0400 '/var/log/audit/audit2.log.*'
chmod: cannot access ‘/var/log/audit/audit2.log.*’: No such file or directory

ERROR - The remediation failed for rule 'xccdf_org.ssgproject.content_rule_file_permissions_var_log_audit'.
INFO - Script incorrect_value_default_file_0600.fail.sh using profile (all) OK
ERROR - Bash remediation for rule xccdf_org.ssgproject.content_rule_file_permissions_var_log_audit has exited with these errors:
Warning: Permanently added '192.168.122.111' (ECDSA) to the list of known hosts.
+ echo 'Remediating rule 1/1: '\''xccdf_org.ssgproject.content_rule_file_permissions_var_log_audit'\'''
Remediating rule 1/1: 'xccdf_org.ssgproject.content_rule_file_permissions_var_log_audit'
+ rpm --quiet -q audit
+ LC_ALL=C
+ grep -iw '^log_file' /etc/audit/auditd.conf
+ FILE=/var/log/audit/audit.log
+ LC_ALL=C
+ grep -m 1 -q '^log_group' /etc/audit/auditd.conf
++ awk -F = '/log_group/ {print $2}' /etc/audit/auditd.conf
++ tr -d ' '
+ GROUP=root
+ '[' root == root ']'
+ chmod 0600 /var/log/audit/audit.log
+ chmod 0400 '/var/log/audit/audit.log.*'
chmod: cannot access ‘/var/log/audit/audit.log.*’: No such file or directory

ERROR - The remediation failed for rule 'xccdf_org.ssgproject.content_rule_file_permissions_var_log_audit'.
```
We should also check the rule itself, it has `rhel9` in prodtype and I believe the condition for `rhel8` also applies for `rhel9`. Overall, the rule needs some refactoring, we don't really want to update if/else conditions in `rule.yml` every time there is a new major RHEL version.

#### SCAP Security Guide Version:
master

#### Operating System Version:
RHEL7 and RHEL9

#### Steps to Reproduce:
```
python3 test_suite.py rule --libvirt qemu:///session ssgts_79 --duplicate-templates --remediate-using bash --datastream ../build/ssg-rhel7-ds.xml file_permissions_var_log_audit
```

### PR DESCRIPTION
**Pull request by yuumasato**
#### Description:

- RHEL7 and RHEL9 should follow the same approach for RHEL8. i.e.:
  - Look for `log_file` in /etc/audit/auditd.conf` and check that file's permissions

#### Rationale:
- Related https://github.com/ComplianceAsCode/content/pull/8808
- RHEL8 STIG: https://stigs.mab879.com/products/rhel8/v1r6/RHEL-08-030070/
- RHEL7 STIG https://stigs.mab879.com/products/rhel7/v3r7/RHEL-07-910055/
- Fixes #8948

### CODE REVIEW

**Comment by yuumasato** [comment]
>     * RHEL8 STIG: https://stigs.mab879.com/products/rhel8/v1r6/RHEL-08-030070/
> 
>     * RHEL7 STIG https://stigs.mab879.com/products/rhel7/v3r7/RHEL-07-910055/
@Mab879 @ggbecker Do you think fix text of this item is correct?
Should it be more like the RHEL7's fixtext?

There is an item more specific about the file's group: https://stigs.mab879.com/products/rhel8/v1r6/RHEL-08-030090/

File: linux_os/guide/system/auditing/auditd_configure_rules/file_permissions_var_log_audit/bash/shared.sh [hunk 1]
```diff
@@ -6,7 +6,7 @@ else
     FILE="/var/log/audit/audit.log"
 fi
 
-{{% if product not in ["ol8", "rhel8"] %}}
+{{% if product not in ["ol8", "rhel7", "rhel8", "rhel9"] %}}
```
Comment (Mab879) [inline linux_os/guide/system/auditing/auditd_configure_rules/file_permissions_var_log_audit/bash/shared.sh:9]:
```suggestion
{{% if product not in ["ol8" ] and 'rhel' not in product %}}
```
Or something similar. So that we don't have to do this again, in the future.

**Review by Mab879 — COMMENTED** [review]
I think this change makes sense.

Maybe we should use `'rhel' in product` or similar so that we will not have to repeat this work for future versions of  RHEL.

**Comment by yuumasato** [comment]
Weird, the test scenarios pass on my machine:
```
time python3 tests/test_suite.py rule  --libvirt qemu:///session rhel9 --datastream build/ssg-rhel9-ds.xml --dontclean file_permissions_var_log_audit
WARNING - You call Automatus using the legacy 'test_suite.py' script, use the 'automatus.py' instead

Setting console output to log level INFO
INFO - The base image option has not been specified, choosing libvirt-based test environment.
INFO - Logging into /home/wsato/git/content/logs/rule-custom-2022-07-12-1839/test_suite.log
WARNING - Script correct_permissions.pass.sh is not applicable on given platform
WARNING - Script incorrect_permissions.fail.sh is not applicable on given platform
INFO - xccdf_org.ssgproject.content_rule_file_permissions_var_log_audit
INFO - Script correct_value_default_file_0600.pass.sh using profile (all) OK
INFO - Script incorrect_value_default_file_0600.fail.sh using profile (all) OK
INFO - Script correct_value_0600.pass.sh using profile (all) OK
INFO - Script incorrect_value_0600.fail.sh using profile (all) OK

WARNING - You call Automatus using the legacy 'test_suite.py' script, use the 'automatus.py' instead

```

**Comment by vojtapolasek** [comment]
I see that some tet scenarios are missing:
# packages = auditd
Could this be the problem?

**Comment by yuumasato** [comment]
@vojtapolasek Thanks, the CI seems happy now.
