### PR TITLE
Remove groupmems command from ensure_pam_wheel_group_empty rule

### LINKED ISSUE #11203: Fix bash remediation for `ensure_pam_wheel_group_empty` rule in SLE context
The remediation does not work in SLE15 because the `groupmems` command is not found. 

Need to provide an alternative method for modification group membership that is portable for SLE platforms also.

_Originally posted by @marcusburghardt in https://github.com/ComplianceAsCode/content/issues/11192#issuecomment-1757118984_

### LINKED ISSUE #11208: Bash remediation hangs on Ubuntu 20.04/22.04
#### Description of problem:

Bash remediation hangs on command `groupmems -g sugroup -p` on Ubuntu 20.04 and 22.04.
The reasons is that `groupmems -p` on Ubuntu prompts for root's password even when run as root or via sudo.
 (https://bugs.launchpad.net/ubuntu/+source/shadow/+bug/2039541)

This command was introduced in PR #11192 

#### Steps to Reproduce:

1. ./build_product.sh ubuntu2204
2. scp build/bash/ubuntu2204-script-cis_level1_server.sh root@ubuntu2204:
3. ssh root@ubuntu2204 "bash ubuntu2204-script-cis_level1_server.sh"

#### Actual Results:
Remediation hangs on:
```
Remediating rule 63/289: 'xccdf_org.ssgproject.content_rule_ensure_pam_wheel_group_empty'
Password: 
```

#### Expected Results:
Remediation finishes normally.

### PR DESCRIPTION
**Pull request by marcusburghardt**
#### Description:

It was noticed that `groupmems` command, which initially seemed like a handy command, does not work on all distros or behaves differently among distros.
It is better to avoid it and use a more generic approach that works for all distros.

The issue was discovered after https://github.com/ComplianceAsCode/content/pull/11192

#### Rationale:

- More compatibility among products
- Fixes #11203
- Fixes #11208

#### Review Hints:

automatus tests should be enough to test the change.

### CODE REVIEW

File: linux_os/guide/system/accounts/accounts-restrictions/root_logins/ensure_pam_wheel_group_empty/bash/shared.sh [hunk 1]
```diff
@@ -7,4 +7,4 @@ if ! grep -q "^${var_pam_wheel_group_for_su}:[^:]*:[^:]*:[^:]*" /etc/group; then
 fi
 
 # group must be empty
-groupmems -g ${var_pam_wheel_group_for_su} -p
+sed -i -E "s/^(${var_pam_wheel_group_for_su}:[^:]*:[^:]*:)[^:]*/\1/g" /etc/group
```
Comment (teacup-on-rockingchair) [inline linux_os/guide/system/accounts/accounts-restrictions/root_logins/ensure_pam_wheel_group_empty/bash/shared.sh:10]: What is your opinion on using gpasswd instead of sed directly to edit the group file, say:
```
gpasswd -M '' ${var_pam_wheel_group_for_su}
```

Comment (marcusburghardt) [reply linux_os/guide/system/accounts/accounts-restrictions/root_logins/ensure_pam_wheel_group_empty/bash/shared.sh:10]: It should work fine for rhel. It is fine for Ubuntu too @dodys ? If so I would prefer to use the command suggested by @teacup-on-rockingchair instead of directly editing the file.

Comment (mpurg) [reply linux_os/guide/system/accounts/accounts-restrictions/root_logins/ensure_pam_wheel_group_empty/bash/shared.sh:10]: Hi @teacup-on-rockingchair @marcusburghardt 
I checked and it works fine on Ubuntu 20.04 and 22.04.

Comment (marcusburghardt) [reply linux_os/guide/system/accounts/accounts-restrictions/root_logins/ensure_pam_wheel_group_empty/bash/shared.sh:10]: Great. I will update it now.

Comment (marcusburghardt) [reply linux_os/guide/system/accounts/accounts-restrictions/root_logins/ensure_pam_wheel_group_empty/bash/shared.sh]: Done. Thanks @teacup-on-rockingchair and @mpurg

**Comment by mpurg** [comment]
Thanks for the fix @marcusburghardt and @teacup-on-rockingchair. 
I can confirm that profile and rule tests passed for Ubuntu.

**Review by dodys — APPROVED** [review]
lgtm, thanks!
and thanks @mpurg for testing it!

**Review by Mab879 — APPROVED** [review]
LGTM. 

Thanks.

**Comment by Mab879** [comment]
The SLES15 failure is not related to this PR, waving.
