### PR TITLE
fix conflicts of audit rules for privileged commands

### LINKED ISSUE #5984: Rule audit_rules_privileged_commands fails after remediation (RHEL7 STIG)
#### Description of problem:
When remediating `stig` profile on RHEL7 or `ism_o` profile RHEL8 the rule `audit_rules_privileged_commands` is reported as fixed, but an additional scan reports it as failed. This is most likely caused by the following remediations because the rule is reported as fixed during remediation (related to [RHBZ#1750755](https://bugzilla.redhat.com/show_bug.cgi?id=1750755)).

#### SCAP Security Guide Version:
master

#### Operating System Version:
RHEL7 (stig), RHEL8 (ism_o)

### PR DESCRIPTION
**Pull request by vojtapolasek**
#### Description:

- modify audit_rules_privileged_commands to unify with templated rules audit_rules_privileged_commands_*

    - remove checking for perm=x

    - remove remediationg of perm=x

    - unify checks and remediations to use -F key=privileged

#### Rationale:

The "automagic" rule audit_rules_privileged_commands and individual templated rules audit_rules_privileged_commands_*  were not cooperating together, although they are are often selected in one profile. It resulted in one of rules failing although the configuration was actually correct. It also resulted in duplicate Audit rule entries.

- fixes #5984

### CODE REVIEW

**Comment by yuumasato** [comment]
@vojtapolasek So this is a regression after https://github.com/ComplianceAsCode/content/pull/5956?

**Comment by vojtapolasek** [comment]
> @vojtapolasek So this is a regression after #5956?

Only partially. Yes the removal of perm=x was not introduced into the automagic rule, that's true. But additionally there was a problem that the templated rule and the automagic rule used different rule keys.

**Review by yuumasato — CHANGES_REQUESTED** [review]
Test scenarios are failing because the script that generates the correct solution has not been updated.
https://github.com/ComplianceAsCode/content/blob/e5a65a1de7eda39e237401417196e87fbc6ea840/linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands/tests/generate_privileged_commands_rule.sh#L7

And I suggest to add a new `fail` test scenario with audit rules with `-F perm=x`. To assure it removes the `perm` correctly.
In extension of previous PR, I suggest adding similar same test scenario for `audit_rules_privileged_commands_sudo`.

**Comment by vojtapolasek** [comment]
You are right, I forgot to update tests. I fixed it and this led to discovering of a typo in oval. I also updated rule description. I will do separate update for templated audit_rules_privileged_commands rules.

File: shared/bash_remediation_functions/perform_audit_rules_privileged_commands_remediation.sh [hunk 1]
```diff
@@ -103,13 +103,12 @@ do
 		base_search=$(sed -e '/-a always,exit/!d' -e '/-F path='"${sbinary_esc}"'[^[:graph:]]/!d'		\
 				-e '/-F path=[^[:space:]]\+/!d'						\
 				-e '/-F auid>='"${min_auid}"'/!d' -e '/-F auid!=\(4294967295\|unset\)/!d'	\
+				-e '/-F perm=[rwxa]\+/d' \
```
Comment (yuumasato) [inline shared/bash_remediation_functions/perform_audit_rules_privileged_commands_remediation.sh:106]: @vojtapolasek Could you clarify what issue this is fixing?

Comment (yuumasato) [reply shared/bash_remediation_functions/perform_audit_rules_privileged_commands_remediation.sh:106]: The `base_search` still needs to look for audit rules setting up a specific `-F perm=`.
But then, instead of removing the code block below (former lines 130 to 154) the block should be changed to remove the `perm` filter.

Test scenario `augenrules_rules_with_perm_x.fail.sh`  scenario is passing, but in the end it duplicates the audit rules:
```
-a always,exit -F path=/usr/bin/passwd -F perm=x -F auid>=1000 -F auid!=unset -k privileged
...
-a always,exit -F path=/usr/bin/passwd -F auid>=1000 -F auid!=unset -F key=privileged
```

File: shared/bash_remediation_functions/perform_audit_rules_privileged_commands_remediation.sh [hunk 2]
```diff
@@ -127,31 +126,6 @@ do
...
-			then
-
-				# If not, append the 'x' (execute) permission to the existing access type bits
-				access_type="$access_type$exec_access"
-				# Reconstruct the permissions section for the rule
-				new_rule_perm="-F perm=$access_type"
-				# Update existing rule in current audit rules file with the new permission section
-				sed -i "s#${rule_head}\(.*\)${rule_tail}#${rule_head}${new_rule_perm}${rule_tail}#" "$afile"
-
-			fi
```
Comment (yuumasato) [inline shared/bash_remediation_functions/perform_audit_rules_privileged_commands_remediation.sh:129]: Instead of being removed, this block needs to be changed to remove any `-F perm=`.

**Review by yuumasato — CHANGES_REQUESTED** [review]

**Comment by vojtapolasek** [comment]
I modified the remediation. The base_search does not pick rules with perm=x explicitly, I don't think it makes sense here as they are covered by rest of regexes. I modified the remediation so that it removes the perm flag as requested.

**Review by yuumasato — APPROVED** [review]
Thank for addressing he comments, looks good to me.
I found a few typo issues, though.

File: shared/bash_remediation_functions/perform_audit_rules_privileged_commands_remediation.sh [hunk 3]
```diff
@@ -122,10 +122,10 @@ do
 			readarray -t handled_sbinaries < <(grep -o -e "-F path=[^[:space:]]\+" <<< "$concrete_rule")
 			handled_sbinaries=("${handled_sbinaries[@]//-F path=/}")
 
-		# 		Merge the list of such SUID/SGID binaries found in this iteration with global list ignoring duplicates
+			# 		Merge the list of such SUID/SGID binaries found in this iteration with global list ignoring duplicates
```
Comment (yuumasato) [inline shared/bash_remediation_functions/perform_audit_rules_privileged_commands_remediation.sh:125]:
```suggestion
			# Merge the list of such SUID/SGID binaries found in this iteration with global list ignoring duplicates
```
