### PR TITLE
Drop usage of pam_faillock rules from SLE12 platform

### LINKED ISSUE #9115: The pam_faillock module was wrongly used as basis for pam related restriction rules for SLE platforms.
#### Share the context

The pam_faillock module was wrongly used as basis for pam related restriction rules for SLE platforms. The pam_tally2 should be used instead. Credit goes to @marcusburghardt for finding and handling that initally in the context of #7564

#### Description of problem:

pam_faillock module is not installed by default on SUSE's SLE platforms and pam_tally module rules should be used instead.

#### Proposed change:

Review current rules used in SLE platform profiles that rely on pam_faillock and replace them with pam_tally

#### References:

1. https://documentation.suse.com/sles/15-SP2/html/SLES-all/sec-sec-user-management.html
2. #7564
1. #9104

### PR DESCRIPTION
**Pull request by teacup-on-rockingchair**
#### Description:

- Use alternate rules based on pam_tally2 module present in SLE12 platform instead of pam_faillock which is not available

#### Rationale:
- Replace usage of accounts_passwords_pam_faillock_deny with accounts_passwords_pam_tally2 rule for SLE platforms
- Replace accounts_passwords_pam_faillock_unlock_time with accounts_passwords_pam_tally2_unlock_time for SLE platforms
- Replace accounts_passwords_pam_faillock_deny_root with accounts_passwords_pam_tally2_deny_root for SLE platform
- Add accounts_passwords_pam_tally2 rule instead of accounts_passwords_pam_faillock_deny
- Drop accounts_passwords_pam_faillock_interval rule for SLE12 platform.  Unfortunately no pam_tally2 alternative found for this functionality, so until pam_faillock is not ported to SLE12 as in SLE15, better to disable the rule

- Fixes #9115

### CODE REVIEW

**Comment by marcusburghardt** [comment]
There is an issue with the same CCE used in two rules:
```
 44/173 Test  #44: unique-cces .........................................................***Failed    0.39 sec

cce CCE-91546-2 is included in files: 
 - linux_os/guide/system/selinux/selinux_policytype/rule.yml
 - linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_deny_root/rule.yml
```

File: linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_deny_root/bash/shared.sh [hunk 1]
```diff
@@ -0,0 +1,9 @@
+# platform = multi_platform_sle,multi_platform_ubuntu
+# reboot = false
+# strategy = restrict
+# complexity = low
+# disruption = low
+
+{{{ bash_ensure_pam_module_options('/etc/pam.d/common-auth', 'auth', 'required', 'pam_tally2.so', 'even_deny_root', '', '') }}}
```
Comment (marcusburghardt) [inline linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_deny_root/bash/shared.sh:7]: I recommend to use the `bash_ensure_pam_module_option` macro instead of the `bash_ensure_pam_module_options` (with s). Besides some issues with this macro, recently, a considerable work was done to refactor the PAM related macros, making them more robust, flexible and aligned between Ansible and Bash.

File: linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_deny_root/ansible/shared.yml [hunk 2]
```diff
@@ -0,0 +1,68 @@
+# platform = multi_platform_sle,multi_platform_ubuntu
+# reboot = false
+# strategy = restrict
+# complexity = low
+# disruption = low
+
+- name: Check to see if pam_tally2.so is configured in /etc/pam.d/common-auth
```
Comment (marcusburghardt) [inline linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_deny_root/ansible/shared.yml:7]: You can use the Ansible macros for PAM settings: `ansible_ensure_pam_module_option`
This would make this remediation much simpler and also aligned with other PAM rules.

File: linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_unlock_time/ansible/shared.yml [hunk 3]
```diff
@@ -0,0 +1,50 @@
+# platform = multi_platform_sle,multi_platform_ubuntu
+# reboot = false
+# strategy = restrict
+# complexity = low
+# disruption = low
+
+{{{ ansible_instantiate_variables("var_accounts_passwords_pam_tally2_unlock_time") }}}
+
+- name: Check to see if pam_tally2.so is configured in /etc/pam.d/common-auth
```
Comment (marcusburghardt) [inline linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_unlock_time/ansible/shared.yml:9]: You can use the Ansible macros for PAM settings: `ansible_ensure_pam_module_option`
This would make this remediation much simpler and also aligned with other PAM rules.

File: linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_unlock_time/bash/shared.sh [hunk 4]
```diff
@@ -0,0 +1,11 @@
+# platform = multi_platform_sle,multi_platform_ubuntu
+# reboot = false
+# strategy = restrict
+# complexity = low
+# disruption = low
+
+{{{ bash_instantiate_variables("var_accounts_passwords_pam_tally2_unlock_time") }}}
+# Use a non-number regexp to force update of the value of the deny option
+{{{ bash_ensure_pam_module_options('/etc/pam.d/common-auth', 'auth', 'required', 'pam_tally2.so', 'unlock_time', '${var_accounts_passwords_pam_tally2_unlock_time}', "${var_accounts_passwords_pam_tally2_unlock_time}") }}}
```
Comment (marcusburghardt) [inline linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_unlock_time/bash/shared.sh:9]: I recommend to use the `bash_ensure_pam_module_option` macro instead of the `bash_ensure_pam_module_options` (with s). More details in the previous comment.

File: linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_unlock_time/bash/shared.sh [hunk 5]
```diff
@@ -0,0 +1,11 @@
...
+
+{{{ bash_ensure_pam_module_options('/etc/pam.d/common-account', 'account', 'required', 'pam_tally2.so', '', '', '') }}}
```
Comment (marcusburghardt) [inline linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_unlock_time/bash/shared.sh:11]: I recommend to use the `bash_ensure_pam_module_option` macro instead of the `bash_ensure_pam_module_options` (with s). More details in the previous comment.

File: linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_unlock_time/oval/shared.xml [hunk 6]
```diff
@@ -0,0 +1,46 @@
...
+    <ind:instance datatype="int" operation="greater than or equal">1</ind:instance>
+  </ind:textfilecontent54_object>
+
+  <ind:textfilecontent54_state id="state_accounts_passwords_pam_tally2_unlock_time" version="1">
+    <ind:subexpression datatype="int" operation="pattern match" var_ref="var_accounts_passwords_pam_tally2_unlock_time"/>
+  </ind:textfilecontent54_state>
+
+  <ind:textfilecontent54_test id="test_accounts_passwords_pam_tally2_unlock_time_account"
+  check="all" check_existence="all_exist"
+  comment="Verify  configuation of pam_tally2_account" version="1">
```
Comment (marcusburghardt) [inline linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_unlock_time/oval/shared.xml:35]: There is an extra space here. :)

File: linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_deny_root/oval/shared.xml [hunk 7]
```diff
@@ -0,0 +1,40 @@
...
+  <definition class="compliance" id="{{{ rule_id }}}" version="1">
+    {{{ oval_metadata("The root account should be configured to deny access after the number of
+    defined failed attempts has been reached.") }}}
+    <criteria operator="AND" comment="Checks common to both scenarios">
+      <criterion test_ref="test_accounts_passwords_pam_tally2_even_deny_root"
+      comment="Verify deny root configuation of pam_tally2 in common-auth" />
+      <criterion test_ref="test_accounts_passwords_pam_tally2_even_deny_root_account"
+      comment="Verify deny configuation of pam_tally2 in common-account" />
+    </criteria>
+
```
Comment (marcusburghardt) [inline linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_deny_root/oval/shared.xml:11]: Just for style purposes, could remove one extra empty line here, please?

File: linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_deny_root/oval/shared.xml [hunk 8]
```diff
@@ -0,0 +1,40 @@
...
+  </definition>
+
```
Comment (marcusburghardt) [inline linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_deny_root/oval/shared.xml:13]: Just for style purposes, could remove one extra empty line here, please?

File: linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_deny_root/oval/shared.xml [hunk 9]
```diff
@@ -0,0 +1,40 @@
...
+  comment="Verify deny configuation of pam_tally2_account" version="1">
+    <ind:object object_ref="object_accounts_passwords_pam_tally2_even_deny_root_account" />
+  </ind:textfilecontent54_test>
+
+  <ind:textfilecontent54_object id="object_accounts_passwords_pam_tally2_even_deny_root_account" comment="Check deny configuration of pam_tally2" version="1">
+    <ind:filepath>/etc/pam.d/common-account</ind:filepath>
+    <ind:pattern operation="pattern match">^\s*account(?:(?!\n)\s)+required(?:(?!\n)\s)+pam_tally2.so(\s|$)</ind:pattern>
+    <ind:instance datatype="int">1</ind:instance>
+  </ind:textfilecontent54_object>
+
```
Comment (marcusburghardt) [inline linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_deny_root/oval/shared.xml:38]: Just for style purposes, could remove two extra empty line here, please?

File: linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_unlock_time/oval/shared.xml [hunk 10]
```diff
@@ -0,0 +1,46 @@
+<def-group>
+  <definition class="compliance" id="{{{ rule_id }}}" version="1">
+    {{{ oval_metadata("The unlock time after number of failed logins should be set correctly.") }}}
+    <criteria operator="AND" comment="Checks common to both scenarios">
+      <criterion test_ref="test_accounts_passwords_pam_tally2_unlock_time"
+      comment="Verify unlock time configuation of pam_tally2 in common-auth" />
+      <criterion test_ref="test_accounts_passwords_pam_tally2_unlock_time_account"
+      comment="Verify unlock time configuation of pam_tally2 in common-account" />
+    </criteria>
+
```
Comment (marcusburghardt) [inline linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_unlock_time/oval/shared.xml:10]: Just for style purposes, could remove one extra empty line here, please?

File: linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_unlock_time/oval/shared.xml [hunk 11]
```diff
@@ -0,0 +1,46 @@
...
+  </definition>
+
```
Comment (marcusburghardt) [inline linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_unlock_time/oval/shared.xml:12]: Just for style purposes, could remove one extra empty line here, please?

File: linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_unlock_time/oval/shared.xml [hunk 12]
```diff
@@ -0,0 +1,46 @@
...
+  comment="Verify  configuation of pam_tally2_account" version="1">
+    <ind:object object_ref="object_accounts_passwords_pam_tally2_unlock_time_account" />
+  </ind:textfilecontent54_test>
+
+  <ind:textfilecontent54_object id="object_accounts_passwords_pam_tally2_unlock_time_account" comment="Check account configuration of pam_tally2" version="1">
+    <ind:filepath>/etc/pam.d/common-account</ind:filepath>
+    <ind:pattern operation="pattern match">^\s*account(?:(?!\n)\s)+required(?:(?!\n)\s)+pam_tally2.so(\s|$)</ind:pattern>
+    <ind:instance datatype="int">1</ind:instance>
+  </ind:textfilecontent54_object>
+
```
Comment (marcusburghardt) [inline linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_unlock_time/oval/shared.xml:44]: Just for style purposes, could remove two extra empty line here, please?

File: linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_deny_root/tests/pam_tally2_absent_account_config.fail.sh [hunk 13]
```diff
@@ -0,0 +1,5 @@
+#!/bin/bash
+# platform = multi_platform_sle,Ubuntu 20.04
+
+cp -f common-account_pam_tally2_absent /etc/pam.d/common-account
```
Comment (marcusburghardt) [inline linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_deny_root/tests/pam_tally2_absent_account_config.fail.sh:4]: I would suggest to prepare the `/etc/pam.d/common-account` and `/etc/pam.d/common-auth` programmatically in the test scenario scripts themselves instead of keeping example files in the project and copying them. It would be more scalable and would reduce the number of files in the project. Could you consider this option, please? 

Also valid for the `accounts_passwords_pam_tally2_unlock_time` rule.

**Review by marcusburghardt — CHANGES_REQUESTED** [review]

File: linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_unlock_time/oval/shared.xml (hunk 11 above)
Comment (teacup-on-rockingchair) [reply linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_unlock_time/oval/shared.xml:11]: > Just for style purposes, could remove one extra empty line here, please?

:bow: Done in e3f3597

File: linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_deny_root/bash/shared.sh (hunk 1 above)
Comment (teacup-on-rockingchair) [reply linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_deny_root/bash/shared.sh]: :bow: Done in e3f3597

File: linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_deny_root/ansible/shared.yml (hunk 2 above)
Comment (teacup-on-rockingchair) [reply linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_deny_root/ansible/shared.yml]: :bow: Done in e3f3597

File: linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_unlock_time/bash/shared.sh (hunk 4 above)
Comment (teacup-on-rockingchair) [reply linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_unlock_time/bash/shared.sh]: :bow: Done in e3f3597

File: linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_deny_root/oval/shared.xml (hunk 9 above)
Comment (teacup-on-rockingchair) [reply linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_deny_root/oval/shared.xml]: :bow: Done in e3f3597

File: linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_unlock_time/oval/shared.xml (hunk 10 above)
Comment (teacup-on-rockingchair) [reply linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_unlock_time/oval/shared.xml]: :bow: Done in e3f3597

File: linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_unlock_time/oval/shared.xml (hunk 11 above)
Comment (teacup-on-rockingchair) [reply linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_unlock_time/oval/shared.xml:11]: :bow: Done in e3f3597

File: linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_unlock_time/oval/shared.xml (hunk 12 above)
Comment (teacup-on-rockingchair) [reply linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_unlock_time/oval/shared.xml]: :bow: Done in e3f3597

File: linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_deny_root/tests/pam_tally2_absent_account_config.fail.sh (hunk 13 above)
Comment (teacup-on-rockingchair) [reply linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_deny_root/tests/pam_tally2_absent_account_config.fail.sh:4]: :bow: Done in e3f3597

Comment (marcusburghardt) [reply linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_deny_root/tests/pam_tally2_absent_account_config.fail.sh:4]: I meant to remove the following files:
- common-account_pam_tally2_absent
- common-account_pam_tally2_configured
- common-auth_pam_tally2_deny_missing
- common-auth_pam_tally2_even_deny_root_configured
- common-auth_pam_tally2_even_deny_root_missing

These 5 files have between 3 and 5 uncommented lines. I suggested to create the content of `/etc/pam.d/common-account` and `/etc/pam.d/common-auth` directly in the test scripts instead of overwriting them by copying these 5 "templated" files.

Your approach is not wrong but I believe these files are unnecessary. Also there are many commented lines there which are not relevant for testing purposes. If you remove them and generate the content of the PAM files directly in the test scenario scripts (by using echo "line..." >> pam_file, for example), the readability should be improved, making it easier to understand the test scenarios once only a single file would give all the context. It would also be more flexible to maintain the test scenarios and easier to include more test scenarios whenever necessary.

File: linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_deny_root/oval/shared.xml (hunk 8 above)
Comment (marcusburghardt) [reply linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_deny_root/oval/shared.xml:13]: Do you intend to remove this extra empty line too?

**Review by marcusburghardt — CHANGES_REQUESTED** [review]
The `accounts_passwords_pam_tally2_deny_root` rule looks good now but the `accounts_passwords_pam_tally2_unlock_time` rule is still using the "sample" files.

File: linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_deny_root/tests/pam_tally2_absent_account_config.fail.sh (hunk 13 above)
Comment (teacup-on-rockingchair) [reply linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2_deny_root/tests/pam_tally2_absent_account_config.fail.sh]: Change for all new tests the approach to use dynamically generated file contents instead of file copies.

**Review by marcusburghardt — APPROVED** [review]
LGTM. Thanks for the nice work @teacup-on-rockingchair .
